# Change these first
owner: modem7 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
# - GENERAL WEBSITES
  - name: Google
    url: https://www.google.com
  - name: BorgBase
    url: https://www.borgbase.com/
# - BLOGS AND WIKIS
  - name: Wiki
    url: https://omegawiki.modem7.com
    asignee: modem7
  - name: Blog
    url: https://modem7.wordpress.com/
    icon: https://raw.githubusercontent.com/modem7/status/master/static/wp-icon.png
    asignee: modem7
# - PLEX RELATED
  - name: Plex
    url: $PLEX_URL
    icon: https://favicons.githubusercontent.com/plex.tv
    asignee: modem7
  - name: Tautulli
    url: https://tautulli.modem7.com/tautulli
    icon: https://raw.githubusercontent.com/Tautulli/Tautulli/master/data/interfaces/default/images/favicon/favicon.ico
    asignee: modem7
  - name: Overseer
    url: https://overseer.modem7.com
    icon: https://raw.githubusercontent.com/sct/overseerr/develop/public/favicon.ico
    asignee: modem7
  - name: Ombi
    url: https://ombi.modem7.com
    icon: https://raw.githubusercontent.com/Ombi-app/Ombi/develop/src/Ombi/wwwroot/images/favicon/favicon.ico
    asignee: modem7
  - name: Sonarr
    url: $SONARR_URL
    #icon: https://raw.githubusercontent.com/Ombi-app/Ombi/develop/src/Ombi/wwwroot/images/favicon/favicon.ico
    asignee: modem7
  - name: Radarr
    url: $RADARR_URL
    #icon: https://raw.githubusercontent.com/Ombi-app/Ombi/develop/src/Ombi/wwwroot/images/favicon/favicon.ico
    asignee: modem7
  - name: Bazarr
    url: $BAZARR_URL
    #icon: https://raw.githubusercontent.com/Ombi-app/Ombi/develop/src/Ombi/wwwroot/images/favicon/favicon.ico
    asignee: modem7
  - name: NZBHydra2
    url: $HYDRA_URL
    #icon: https://raw.githubusercontent.com/Ombi-app/Ombi/develop/src/Ombi/wwwroot/images/favicon/favicon.ico
    asignee: modem7
# - DASHBOARDS
  - name: Grafana
    url: $GRAFANA_URL
    icon: https://favicons.githubusercontent.com/grafana.com
  - name: Netdata
    url: $NETDATA_URL
    icon: https://raw.githubusercontent.com/netdata/netdata/master/web/gui/static/img/netdata-logomark.svg
    asignee: modem7
  - name: Heimdall
    url: https://alexlane.modem7.com
    icon: https://raw.githubusercontent.com/linuxserver/Heimdall/master/public/favicon.ico
    asignee: modem7
# - SECURITY
  - name: Bitwarden
    url: $BITWARDEN_URL
    icon: https://raw.githubusercontent.com/modem7/status/master/static/bitwarden.png
    asignee: modem7
# - CI/CD
  - name: DroneCI
    url: https://drone.modem7.com
    icon: https://raw.githubusercontent.com/modem7/status/master/static/dronefav.ico
    asignee: modem7
# - PASTEBINS
  - name: Hastebin
    url: $HASTEBIN_URL
    icon: https://raw.githubusercontent.com/modem7/status/master/static/hastebin.png
    asignee: modem7
# - SYSTEM RELATED
  - name: Portainer
    url: $PORTAINER_URL
    icon: https://raw.githubusercontent.com/modem7/status/master/static/portainer.png
    asignee: modem7
  - name: Scrutiny
    url: https://scrutiny.modem7.com/
    icon: https://raw.githubusercontent.com/AnalogJ/scrutiny/master/webapp/frontend/src/assets/images/logo/scrutiny-logo-white.svg
    asignee: modem7

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.modem7.com
  # Theme
#  theme: night
  theme: dark
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Status Page
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "Lex's services status page."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Wiki
      href: https://modem7.com
