# Change these first
owner: modem7 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
#####################
# - GENERAL WEBSITES#
#####################
  - name: BorgBase
    url: https://www.borgbase.com/
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/borgbase.png
# - BLOGS AND WIKIS
  - name: Wiki
    url: https://omegawiki.modem7.com
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/HeimdallIcons/bookstack.png
    asignee: modem7
  - name: Blog
    url: https://modem7.wordpress.com/
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/wordpress.png
    asignee: modem7
#################
# - PLEX RELATED#
#################
  - name: Plex
    url: $PLEX_URL
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/plex.png
    asignee: modem7
  - name: Tautulli
    url: https://tautulli.modem7.com/tautulli
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/HeimdallIcons/tautulli.png
    asignee: modem7
  - name: Overseer
    url: https://overseer.modem7.com
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/HeimdallIcons/overseerr.png
    asignee: modem7
  - name: Sonarr
    url: $SONARR_URL
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/HeimdallIcons/sonarr.png
    asignee: modem7
  - name: Radarr
    url: $RADARR_URL
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/HeimdallIcons/radarr.png
    asignee: modem7
  - name: Prowlarr
    url: $PROWLARR_URL
    icon: https://github.com/Prowlarr/Prowlarr/raw/develop/Logo/32.png
    asignee: modem7
###############
# - DASHBOARDS#
###############
  - name: Grafana
    url: $GRAFANA_URL
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/HeimdallIcons/grafana.png
  - name: Netdata
    url: $NETDATA_URL
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/HeimdallIcons/netdata.png
    asignee: modem7
  - name: Flame
    url: $FLAME_URL
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/flame.png
    asignee: modem7
#############
# - SECURITY#
#############
  - name: Bitwarden
    url: $BITWARDEN_URL
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/bitwarden.png
    asignee: modem7
##########
# - CI/CD#
##########
  - name: DroneCI
    url: https://drone.modem7.com
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/HeimdallIcons/droneci.png
    asignee: modem7
##############
# - PASTEBINS#
##############
  - name: Pastebin
    url: $PASTEBIN_URL
    icon: https://raw.githubusercontent.com/enchant97/hasty-paste/main/paste_bin/static/icon.svg
    asignee: modem7
  - name: XBackbone
    url: $XBACKBONE_URL
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/xbackbone.png
    asignee: modem7
####################
# - SYSTEM SERVICES#
####################
  - name: Pihole
    url: $PIHOLE_URL
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/pihole.png
#  - name: 3CX
#    url: $PBX_URL
#    icon: https://github.com/modem7/MiscAssets/blob/master/Icons/3CX.png
#    asignee: modem7
  - name: Portainer
    url: $PORTAINER_URL
    icon: https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/HeimdallIcons/portainer.png
    asignee: modem7
#  - name: Scrutiny
#    url: https://scrutiny.modem7.com/
#    icon: https://raw.githubusercontent.com/modem7/MiscAssets/4e15c407c685733d112292bca6db868ac3d2c374/Icons/scrutiny.svg
#    asignee: modem7
  - name: Dozzle
    url: $DOZZLE_URL
    icon: https://github.com/modem7/MiscAssets/blob/master/Icons/HeimdallIcons/dozzle.png
    asignee: modem7	

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.modem7.com
  # Theme
#  theme: night
  theme: dark
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Status Page
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "Lex's services status page."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Wiki
      href: https://modem7.com
