# Change these first
owner: modem7 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Plex
    url: https://plex.tv
  - name: Blog
    url: https://omegawiki.modem7.com
    asignee: modem7
    expectedStatusCodes:
      - 403
      - 404
  - name: Plex
    url: $PLEX_URL
    asignee: modem7
    expectedStatusCodes:
      - 403
      - 404
    icon: https://favicons.githubusercontent.com/plex.tv

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.modem7.com
  # Theme
  theme: dark
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "Lex's services status page."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
